engines:
  rubocop:
    enabled: true
  fixme:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - ruby
ratings:
  paths:
    - app/**
    - lib/**
exclude_paths:
  - spec/**/*
  - vendor/**/
