language: ruby
services:
  - postgresql
before_script:
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:test:prepare
  - nvm install 6.2
  - nvm use 6.2
  - npm install -g yarn
  - yarn install
script:
  - npm run lint
  - bundle exec rspec
  - bundle exec codeclimate-test-reporter
env:
  global:
    - NPM_CONFIG_PROGRESS="false"
addons:
  code_climate:
    repo_token: 7874401dea920ec562008f8735921e38a01ff559f4377bcedbdba1a8b54145ca
cache:
  bundler: true
  directories:
  - node_modules
  - $HOME/.yarn-cache
deploy:
  provider: heroku
  api_key:
    secure: CHFON45m9nMNIeVqKbAnGu3yRRHPQMr9rOYtXQIqPWX/I/xg1WBOUyLWGrTLnMwxBBU4W18dmUvDh0C0USop7WrWFIzyEs2Gkm+kLEI/pwrmsi/vewS/m3WxirjYPA4xXn5eq+jE5qIa4TkKPV1DQzq1n73GvH/267I2er39XZM=
  app: porkchop-prod
  on:
    repo: PorkChopClub/porkchop
  run:
    - "rake db:migrate"
    - restart
