language: elixir
elixir:
  - 1.1.0
otp_release:
  - 18.0
script:
  - ( cd chop && mix deps.get && mix test )
  - ( cd legacy && rvm use 2.2 && bundle && bundle exec rake db:test:prepare && bundle exec rspec )
