Player.create! name: "Jared Norman", avatar_url: "http://i.imgur.com/idCKWDT.png"
Player.create! name: "Gray Gilmore", avatar_url: "http://i.imgur.com/s7d1vVo.png"
Player.create! name: "Sean Taylor"
Player.create! name: "Naomi Aro"
Player.create! name: "Clarke Brunsdon"
Player.create! name: "Kyria Brown"
Player.create! name: "Adam Mueller", avatar_url: "http://i.imgur.com/2jhmPJv.png"
Player.create! name: "Chris Todorov"
Player.create! name: "Richard Wilson"
Player.create! name: "Brendan Deere", avatar_url: "http://i.imgur.com/RSPZBIV.png"
Player.create! name: "Kevin Attfield"
Player.create! name: "John Hawthorn"
User.create! username: 'admin', uid: 'admin@example.com', admin: true, provider: 'developer'
