Player.create! name: "Jared Norman", avatar_url: "/avatars/jared.png"
Player.create! name: "Gray Gilmore", avatar_url: "http://i.imgur.com/s7d1vVo.png"
Player.create! name: "Adam Mueller", avatar_url: "http://i.imgur.com/2jhmPJv.png"
Player.create! name: "Chris Todorov", avatar_url: "https://dl.dropboxusercontent.com/u/499982/chris.png"
Player.create! name: "John Hawthorn", avatar_url: "http://i.hawth.ca/u/john2000.png"
