Player.create! name: "Jared Norman", avatar_url: "/avatars/jared.png"
Player.create! name: "Gray Gilmore", avatar_url: "http://i.imgur.com/s7d1vVo.png"
Player.create! name: "Sean Taylor"
Player.create! name: "Naomi Aro"
Player.create! name: "Clarke Brunsdon"
Player.create! name: "Kyria Brown", avatar_url: "http://i.imgur.com/7sQkWIx.png"
Player.create! name: "Adam Mueller", avatar_url: "http://i.imgur.com/2jhmPJv.png"
Player.create! name: "Chris Todorov", avatar_url: "https://dl.dropboxusercontent.com/u/499982/chris.png"
Player.create! name: "Richard Wilson", avatar_url: "http://i.imgur.com/fp1xA17.png"
Player.create! name: "Brendan Deere", avatar_url: "http://i.imgur.com/RSPZBIV.png"
Player.create! name: "Kevin Attfield"
Player.create! name: "John Hawthorn", avatar_url: "http://i.hawth.ca/u/john2000.png"
Player.create! name: "Alex Blackie", avatar_url: "http://i.imgur.com/WxAaeGs.png"
User.create! username: 'admin', uid: 'admin@example.com', admin: true, provider: 'developer'
