default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: porkchop_development

test:
  <<: *default
  database: porkchop_test

production:
  <<: *default
  database: porkchop_production
